spring:
  application:
    name: Flirtopia
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Flirtopia?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  redis: #spring-configuration-metadata.json
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 16
        max-active: 32
        max-idle: 8
        max-wait: 2000
    timeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
com:
  flirtopia:
    mail:
      user: flortopia_service@gmail.com
      salt: flirtopia
      encry-pwd: xxxx
      from: flortopia_service@gmail.com
    openai:
        token: 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
stripe:
  apiKey: xxxx
  webhookSecret: xxx