# 开启优雅停止 Web 容器，默认为 IMMEDIATE：立即停止
server:
  tomcat:
    accept-count: 100
    threads:
      # 1核2g内存为200,4核8g内存为800
      max: 800
      # 最小空闲线程数量，保证线程池中一直有最少100个线程，防止流量激增
      min-spare: 100
    # 连接超时时间
    connection-timeout: 10000
    # 最大连接数，可以适应 APR 模式
    max-connections: 8192
  shutdown: graceful
  max-http-header-size: 20000

spring:
  application:
    name: Flirtopia
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://flirtoipa.ctnhss14ljhr.us-east-2.rds.amazonaws.com:3306/flirtopia?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: liuweikai
  redis: #spring-configuration-metadata.json
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 16
        max-active: 32
        max-idle: 8
        max-wait: 2000
    timeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
com:
  flirtopia:
    mail:
      user: flirtopiaservice@gmail.com
      app-pwd: pwtaixikpzkbntrj
      from: flirtopiaservice@gmail.com
stripe:
  apiKey: bt4Ajnyh+8abT3qwAj6H4m3eJseEN9deK93v9Gw3p7eKGrQjf3kC6R9T3BBNP2wVYKtHzBm1v+3lE7iZdLe4gJN524c42iQ+YA45sp+WqfoI2d4Y/4BmeXEFfoyI2WGFkJBw7HtuSyBgTsVjs6N1bw==
  webhookSecret: VQhHvDCi9JynkBiqFpG9QaUfUUhyFqRQoEwgRiyP59vxblJQLVZ5ew==