# 开启优雅停止 Web 容器，默认为 IMMEDIATE：立即停止
server:
  shutdown: graceful
  max-http-header-size: 20000

spring:
  application:
    name: Flirtopia
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://flirtopia-v1.cmalodbmmmwo.ap-southeast-2.rds.amazonaws.com:3306/flirtopia?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: liuweikai
  redis: #spring-configuration-metadata.json
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 16
        max-active: 32
        max-idle: 8
        max-wait: 2000
    timeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
com:
  flirtopia:
    mail:
      user: flirtopiaservice@gmail.com
      app-pwd: pwtaixikpzkbntrj
      from: flirtopiaservice@gmail.com
stripe:
  apiKey: sk_test_51NPOMIBegHkiPVmEtyhXq3hPFQrXrx9oTVeobQ07bG7PKCloN8uAk4YVq9kPBbb46SgeMocpKSD9TQwuhGcJv1St000ngXvqSb
  webhookSecret: whsec_tMGmi5ui6dpSwO6oNaSoqNIUxaMP7xu8