spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## ??????????????????????serverTimezone=UT
    url: jdbc:mysql://localhost:3306/happychat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
